<<<<<<< HEAD
git
=======
services:
  - type: web
    name: smart-dictionary
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
>>>>>>> ac6458bac8abc6337e62b1bc0e7e38cb68c66562
